proxies:
# --- Proxy Groups --- #
proxy-groups:
  - name: Server List ğŸ”‘
    type: select
    proxies: [ID-1 ğŸ‡®ğŸ‡© âš¡, ID-2 ğŸ‡®ğŸ‡© âš¡, SG-1 ğŸ‡¸ğŸ‡¬ âš¡, SG-2 ğŸ‡¸ğŸ‡¬ âš¡, Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸, Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸, Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
  - name: Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use: [LB-ID ğŸ‡®ğŸ‡©]
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use: [LB-SG ğŸ‡¸ğŸ‡¬]
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: Load-Balance Reguler âš–ï¸
    type: load-balance
    strategy: round-robin
    disable-udp: false
    proxies: [Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ]
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: ID-1 ğŸ‡®ğŸ‡© âš¡
    type: select
    use: [ID-1 ğŸ‡®ğŸ‡©]
  - name: ID-2 ğŸ‡®ğŸ‡© âš¡
    type: select
    use: [ID-2 ğŸ‡®ğŸ‡©]
  - name: SG-1 ğŸ‡¸ğŸ‡¬ âš¡
    type: select
    use: [SG-1 ğŸ‡¸ğŸ‡¬]
  - name: SG-2 ğŸ‡¸ğŸ‡¬ âš¡
    type: select
    use: [SG-2 ğŸ‡¸ğŸ‡¬]
  - name: Kuota Reguler 1 ğŸ›œ
    type: select
    interface-name: eth1
    proxies: [DIRECT]
  - name: Kuota Reguler 2 ğŸ›œ
    type: select
    interface-name: eth2
    proxies: [DIRECT]
  - name: Games ğŸ•¹ï¸
    type: select
    disable-udp: false
    proxies: [DIRECT, Server List ğŸ”‘, Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸, Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸, ID-1 ğŸ‡®ğŸ‡© âš¡, ID-2 ğŸ‡®ğŸ‡© âš¡, SG-1 ğŸ‡¸ğŸ‡¬ âš¡, SG-2 ğŸ‡¸ğŸ‡¬ âš¡, Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
  - name: Port-Games ğŸ•¹ï¸
    type: select
    disable-udp: false
    proxies: [DIRECT, Server List ğŸ”‘, Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸, Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸, ID-1 ğŸ‡®ğŸ‡© âš¡, ID-2 ğŸ‡®ğŸ‡© âš¡, SG-1 ğŸ‡¸ğŸ‡¬ âš¡, SG-2 ğŸ‡¸ğŸ‡¬ âš¡, Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
  - name: Rule Social Media â¤ï¸
    type: select
    disable-udp: false
    proxies: [DIRECT, Server List ğŸ”‘, Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸, Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸, ID-1 ğŸ‡®ğŸ‡© âš¡, ID-2 ğŸ‡®ğŸ‡© âš¡, SG-1 ğŸ‡¸ğŸ‡¬ âš¡, SG-2 ğŸ‡¸ğŸ‡¬ âš¡, Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
  - name: Rule Streaming â¤ï¸
    type: select
    disable-udp: false
    proxies: [DIRECT, Server List ğŸ”‘, Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸, Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸, ID-1 ğŸ‡®ğŸ‡© âš¡, ID-2 ğŸ‡®ğŸ‡© âš¡, SG-1 ğŸ‡¸ğŸ‡¬ âš¡, SG-2 ğŸ‡¸ğŸ‡¬ âš¡, Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
  - name: Rule Umum â¤ï¸
    type: select
    disable-udp: false
    proxies: [DIRECT, Server List ğŸ”‘, Load-Balance ID ğŸ‡®ğŸ‡© âš–ï¸, Load-Balance SG ğŸ‡¸ğŸ‡¬ âš–ï¸, ID-1 ğŸ‡®ğŸ‡© âš¡, ID-2 ğŸ‡®ğŸ‡© âš¡, SG-1 ğŸ‡¸ğŸ‡¬ âš¡, SG-2 ğŸ‡¸ğŸ‡¬ âš¡, Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
  - name: Rule Reguler â¤ï¸
    type: select
    disable-udp: false
    proxies: [Kuota Reguler 1 ğŸ›œ, Kuota Reguler 2 ğŸ›œ, Load-Balance Reguler âš–ï¸]
# --- Proxy Providers --- #
proxy-providers:
  SG-1 ğŸ‡¸ğŸ‡¬:
    type: file
    path: "./proxy_provider/sg1.yaml"
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  SG-2 ğŸ‡¸ğŸ‡¬:
    type: file
    path: "./proxy_provider/sg2.yaml"
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  ID-1 ğŸ‡®ğŸ‡©:
    type: file
    path: "./proxy_provider/id1.yaml"
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  ID-2 ğŸ‡®ğŸ‡©:
    type: file
    path: "./proxy_provider/id2.yaml"
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  LB-SG ğŸ‡¸ğŸ‡¬:
    type: file
    path: "./proxy_provider/lbsg.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  LB-ID ğŸ‡®ğŸ‡©:
    type: file
    path: "./proxy_provider/lbid.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
 # --- Rule Providers --- #
rule-providers:
#rule-providers yang dikecualikan: Pay, Umum
  Pay:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/abrarilaviarsy/openclash/main/rule_provider/rule_payment.yaml
    path: "./rule_provider/rule_payment.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Game:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Gaming:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_gaming.yaml
    path: "./rule_provider/rule_gaming.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Port-Games:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_portgames.yaml
    path: "./rule_provider/rule_portgames.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  TikTok:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Google-Play-Store:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_playstore.yaml
    path: "./rule_provider/rule_playstore.yaml"
    interval: 86400  # Pembaruan setiap 4 jam sekali
  Telegram-CIDR:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_telegramcidr.yaml
    path: "./rule_provider/rule_telegramcidr.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Telegram:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_telegram.yaml
    path: "./rule_provider/rule_telegram.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Metaverse:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_metaverse.yaml
    path: "./rule_provider/rule_metaverse.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_umum.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Direct:
    type: http
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_direct.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  False-Positive:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_falsepositive.yaml
    path: "./rule_provider/rule_falsepositive.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  YouTube:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_youtube.yaml
    path: "./rule_provider/rule_youtube.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Speedtest:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_speedtest.yaml
    path: "./rule_provider/rule_speedtest.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Twitter:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_twitter.yaml
    path: "./rule_provider/rule_twitter.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Twitch:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_twitch.yaml
    path: "./rule_provider/rule_twitch.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Netflix:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_netflix.yaml
    path: "./rule_provider/rule_netflix.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Prime-Video:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_primevideo.yaml
    path: "./rule_provider/rule_primevideo.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Disney+:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_disneyplus.yaml
    path: "./rule_provider/rule_disneyplus.yaml"
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Streaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_streaming.yaml"
    url: https://raw.githubusercontent.com/abrarilaviarsy/openclash/main/rule_provider/rule_streaming.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Indonesia-Service:
    type: http
    behavior: classical
    path: "./rule_provider/rule_indo.yaml"
    url: https://raw.githubusercontent.com/abrarilaviarsy/openclash/main/rule_provider/rule_indo.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Instagram:
    type: http
    behavior: domain
    path: "./rule_provider/rule_instagram.yaml"
    url: https://raw.githubusercontent.com/abrarilaviarsy/openclash/main/rule_provider/rule_instagram.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  GoogleFCM:
    type: http
    behavior: domain
    path: "./rule_provider/rule_googlefcm.yaml"
    url: https://raw.githubusercontent.com/abrarilaviarsy/openclash/main/rule_provider/rule_googlefcm.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Video-Conferences:
    type: http
    behavior: classical
    path: "./rule_provider/rule_videoconferences.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_videoconferences.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
  Custom-Rule-Direct:
    type: http
    behavior: classical
    path: "./rule_provider/customrule_direct.yaml"
    url: https://raw.githubusercontent.com/abrarilaviarsy/openclash/main/rule_provider/customrule_direct.yaml
    interval: 86400 # Pembaruan setiap 4 jam sekali
rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - DST-PORT,22,Server List ğŸ”‘
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  # Rule Games
  - RULE-SET,Game,Games ğŸ•¹ï¸
  - RULE-SET,Gaming,Games ğŸ•¹ï¸
  - RULE-SET,Port-Games,Port-Games ğŸ•¹ï¸
  # Rule Social Media
  - RULE-SET,TikTok,Rule Social Media â¤ï¸
  - RULE-SET,Telegram-CIDR,Rule Social Media â¤ï¸
  - RULE-SET,Telegram,Rule Social Media â¤ï¸
  - RULE-SET,Metaverse,Rule Social Media â¤ï¸
  - RULE-SET,Twitter,Rule Social Media â¤ï¸
  - RULE-SET,Instagram,Rule Social Media â¤ï¸
  # Rule Streaming
  - RULE-SET,YouTube,Rule Streaming â¤ï¸
  - RULE-SET,Twitch,Rule Streaming â¤ï¸
  - RULE-SET,Netflix,Rule Streaming â¤ï¸
  - RULE-SET,Disney+,Rule Streaming â¤ï¸
  - RULE-SET,Streaming,Rule Streaming â¤ï¸
  - RULE-SET,Prime-Video,Rule Streaming â¤ï¸
  # Rule Umum
  - RULE-SET,Video-Conferences,Rule Umum â¤ï¸
  - RULE-SET,Google-Play-Store,Rule Umum â¤ï¸
  - RULE-SET,False-Positive,Rule Umum â¤ï¸
  - RULE-SET,Speedtest,Rule Umum â¤ï¸
  # Rule Direct/Kuota Reguler
  - RULE-SET,Direct,Rule Reguler â¤ï¸
  - RULE-SET,Indonesia-Service,Rule Reguler â¤ï¸
  - RULE-SET,Custom-Rule-Direct,Rule Reguler â¤ï¸
  - RULE-SET,GoogleFCM,Rule Reguler â¤ï¸
  ###
  - MATCH,Server List ğŸ”‘
 # Settingan Konfigurasi (Opsional), hapus jika tidak diperlukan
unified-delay: true
